DECLARE @StateTaxRecordCount INT
SET @StateTaxRecordCount = (SELECT COUNT(ID) FROM StateTax) 
IF @StateTaxRecordCount <= 0
BEGIN
	INSERT INTO StateTax (Name,[Percent]) VALUES ('AL','9.22')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('AK','1.76')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('AZ','8.40')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('AR','9.51')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('CA','8.68')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('CT','7.72')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('DE','0.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('DC','6.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('FL','7.08')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('GA','7.32')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('HI','4.44')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('ID','6.03')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('IL','8.82')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('IN','7.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('IA','6.94')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('KS','8.69')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('LA','9.52')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('ME','5.50')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('MD','6.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('MA','6.25')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('MI','6.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('MS','7.07')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('MO','8.25')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('MT','0.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('NE','6.94')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('NV','8.23')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('NH','0.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('NJ','6.06')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('NM','7.83')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('NY','8.52')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('NC','6.98')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('ND','6.96')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('OH','7.23')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('OK','8.95')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('OR','0.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('PA','6.34')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('RI','7.00')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('SC','7.46')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('SD','6.40')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('TN','9.55')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('TX','8.19')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('UT','7.19')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('VT','6.24')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('VA','5.73')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('WA','9.23')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('WV','6.50')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('WI','5.43')
	INSERT INTO StateTax (Name,[Percent]) VALUES ('WY','5.33')
END